[package]
name = "xaskpass"
description = "A lightweight passphrase dialog"
repository = "https://github.com/user827/xaskpass"
license = "Apache-2.0"
keywords = ["askpass", "password", "x11", "xcb"]
version = "1.8.6"
authors = ["user827"]
readme = "README.md"
edition = "2018"
exclude = [
  "/.gitignore",
  "/RELEASE-CHECKLIST.md"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0" }
tokio = { version = "1.10", features = [ "net", "rt", "macros", "signal", "time" ] }
x11rb = { version = "0.8", features = [ "allow-unsafe-code", "present", "xkb", "render" ] }
pangocairo = "0.14"
pangocairo-sys = "0.14"
pango = "0.14"
pango-sys = "0.14"
libc = "0.2"
clap = "3.0.0-beta.4"
log = "0.4"
env_logger = { version = "0.8" }
cairo-rs = { version = "0.14", features = ["xcb"] }
cairo-sys-rs = { version = "0.14" }
gethostname = "0.2"
secstr = "0.4"
zeroize = "1.4"
color_processing = "0.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
xdg = "2.2"
rand = "0.8"

[build-dependencies]
pkg-config = "0.3"
bindgen = "0.59"
image = "0.23"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
