[package]
name = "xaskpass"
description = "A lightweight passphrase dialog"
repository = "https://github.com/user827/xaskpass"
license = "Apache-2.0"
keywords = ["askpass", "password", "x11", "xcb"]
version = "1.8.5"
authors = ["user827"]
readme = "README.md"
edition = "2018"
exclude = [
  "/.gitignore",
  "/RELEASE-CHECKLIST.md"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "*" }
tokio = { version = "*", features = [ "net", "rt", "macros", "signal", "time" ] }
x11rb = { version = "*", features = [ "allow-unsafe-code", "present", "xkb", "render" ] }
pangocairo = "*"
pangocairo-sys = "*"
pango = "*"
pango-sys = "*"
libc = "*"
clap = "3.0.0-beta.2"
log = "*"
env_logger = { version = "*" }
cairo-rs = { version = "*", features = ["xcb"] }
cairo-sys-rs = { version = "*" }
gethostname = "*"
secstr = "*"
zeroize = "*"
color_processing = "*"
serde = { version = "*", features = ["derive"] }
toml = "*"
xdg = "*"
rand = "*"

[build-dependencies]
pkg-config = "*"
bindgen = "*"
image = "*"
